# -*- coding: utf-8 -*-
"""
A simple script to create CMT compliant Tab Delimited text files used for inviting
Reviewers in CMT.

Each line of this file contains the following tab delimited fields:
First Name - Middle Initial (optional) - Last Name - Email - Organization

The sources used to extract Reviewers are different:
- previous IJCNN Reviewers from a file generated by the EDAS system
- previous IJCNN Authors (up to six) from a file generated by the EDAS system
- previous Reviewers from other conferences from a file generated by the CMT system
- self-nominated Reviewers from a file generated by Google form.

A check on the validity of the email addresses has also been performed.

Created on Sun Feb 26 18:35:52 2023

@author: Michele Scarpiniti -- DIET Dpt. (Sapienza University of Rome)
"""

import pandas as pd
import IJCNN_utils as ut


# %% 1. Extracting IJCNN 2024 Reviewers

# Setting the file names
path = './data/'
dest = './report/'
input_file  = path + 'ijcnn2024_reviewers.xlsx'
output_file = dest + 'Reviewers1'


# Reading the input file
df1 = pd.read_excel(input_file)


# Renaming columns name
df1.rename(columns={"Given name":"First Name", "Surname":"Last Name",
                   "Affiliation":"Organization", "Email address":"Email"},
           inplace=True)


# Selecting the needed information, removing NaN rows
df1.dropna(inplace=True)


# Removing duplicated rows
df1 = df1.drop_duplicates(subset=['First Name', 'Last Name', 'Organization'])


# Menaging the middle name initial
first_name, mid_name = ut.split_firstName(df1)

df1.drop(['First name'], axis=1, inplace=True)
df1.insert(0, 'First Name', first_name)
df1.insert(1, 'Middle Initial', mid_name)


# Dropping the 'Full name' column
df1.drop(['Full name'], axis=1, inplace=True)



# Reordering columns
columns_titles = ['First Name', 'Middle Initial', 'Last Name', 'Email', 'Organization']
df1 = df1.reindex(columns=columns_titles)


# Print the number of Reviewers
N_Rev_1 = len(df1)
print('Number of Reviewers:', N_Rev_1)


# Check for email validity
em = list(df1['Email'])
_, res = ut.test_emails(em)

# Print the incorrect email addresses
if len(res) > 0:
    print("Please, check the following email addresses:")
    for n, j in enumerate(res):
        print(n+1, ':', em[j])
else:
    print("All email addresses are correct")


# Write to the "Tab Delimited" text file
df1.to_csv(output_file+'.txt', sep='\t', header=False, index=False)
df1.to_excel(output_file+'.xlsx', index=False)



# %% 2. Extracting IJCNN 2024 Authors

# Setting the file names
path = './data/'
dest = './report/'
input_file  = path + 'ijcnn2024_papers.xlsx'
output_file = dest + 'Reviewers2'


# Reading the input file
data = pd.read_excel(input_file)


# --- Extracting the first six Authors -------------------------------------
DFs = []

for i in range(1,7):

    # Columns to preserve
    columns_select = ['Author ' + str(i) + ' given',
                      'Author ' + str(i) + ' surname',
                      'Author ' + str(i) + ' affiliation',
                      'Author ' + str(i) + ' email']

    # Selecting the needed information, removing NaN rows
    dfa = data[columns_select]
    dfa.dropna(inplace=True)

    # Renaming columns name
    columns_name = {"Author " + str(i) + " given":"First Name",
                    "Author " + str(i) + " surname":"Last Name",
                    "Author " + str(i) + " affiliation":"Organization",
                    "Author " + str(i) + " email":"Email"}
    dfa.rename(columns=columns_name, inplace=True)


    # Removing duplicated rows
    dfa = dfa.drop_duplicates(subset=['First Name', 'Last Name', 'Organization'])

    # Inserting the "Middle Name" column
    first_name, mid_name = ut.split_firstName(dfa)

    dfa.drop(['First Name'], axis=1, inplace=True)
    dfa.insert(0, 'First Name', first_name)
    dfa.insert(1, 'Middle Initial', mid_name)


    # Reordering columns
    columns_titles = ['First Name', 'Middle Initial', 'Last Name', 'Email', 'Organization']
    dfa = dfa.reindex(columns=columns_titles)

    DFs.append(dfa)


# Concatenating all authors
df2 = pd.concat(DFs, axis=0)


# Removing duplicated rows
df2 = df2.drop_duplicates(subset=['First Name', 'Last Name', 'Organization'])


# Print the number of Reviewers
N_Rev_2 = len(df2)
print('Number of Reviewers:', N_Rev_2)


# Check for email validity
em = list(df2['Email'])
_, res = ut.test_emails(em)

# Print the incorrect email addresses
if len(res) > 0:
    print("Please, check the following email addresses:")
    for n, j in enumerate(res):
        print(n+1, ':', em[j])
else:
    print("All email addresses are correct")


# Write to the "Tab Delimited" text file
df2.to_csv(output_file+'.txt', sep='\t', header=False, index=False)
df2.to_excel(output_file+'.xlsx', index=False)



# %% 3. Importing MLSP 2023 Reviewers

# Setting the file names
path = './data/'
dest = './report/'
input_file  = path + 'mlsp2023_reviewers.xlsx'
output_file = dest + 'Reviewers3'


# Reading the input file
df3 = pd.read_excel(input_file)


# Print the number of Reviewers
N_Rev_3 = len(df3)
print('Number of Reviewers:', N_Rev_3)


# Check for email validity
em = list(df3['Email'])
_, res = ut.test_emails(em)

# Print the incorrect email addresses
if len(res) > 0:
    print("Please, check the following email addresses:")
    for n, j in enumerate(res):
        print(n+1, ':', em[j])
else:
    print("All email addresses are correct")


# Write to the "Tab Delimited" text file
df3.to_csv(output_file+'.txt', sep='\t', header=False, index=False)
df3.to_excel(output_file+'.xlsx', index=False)



# %% 4. Extracting ICASSP 2025 Reviewers

# Setting the file names
path = './data/'
dest = './report/'
input_file  = path + 'icassp2025_reviewers.xlsx'
output_file = dest + 'Reviewers4'


# Reading the input file
df4 = pd.read_excel(input_file)


# Selecting the needed information, removing NaN rows
df4.dropna(inplace=True)


# Removing duplicated rows
df4 = df4.drop_duplicates(subset=['First Name', 'Last Name', 'Organization'])


# Menaging the middle name initial
first_name, mid_name = ut.split_firstName(df4)

df4.drop(['First name'], axis=1, inplace=True)
df4.insert(0, 'First Name', first_name)
df4.insert(1, 'Middle Initial', mid_name)


# Reordering columns
columns_titles = ['First Name', 'Middle Initial', 'Last Name', 'Email', 'Organization']
df4 = df4.reindex(columns=columns_titles)


# Print the number of Reviewers
N_Rev_4 = len(df4)
print('Number of Reviewers:', N_Rev_4)


# Check for email validity
em = list(df4['Email'])
_, res = ut.test_emails(em)

# Print the incorrect email addresses
if len(res) > 0:
    print("Please, check the following email addresses:")
    for n, j in enumerate(res):
        print(n+1, ':', em[j])
else:
    print("All email addresses are correct")


# Write to the "Tab Delimited" text file
df4.to_csv(output_file+'.txt', sep='\t', header=False, index=False)
df4.to_excel(output_file+'.xlsx', index=False)



# %% 5. Importing self-nominated Reviewers

# Setting the file names
path = './data/'
dest = './report/'
input_file  = path + 'self_reviewers.xlsx'
output_file = dest + 'Reviewers5'


# Reading the input file
df5 = pd.read_excel(input_file)


# Removing first column
columns_drop = ['Informazioni cronologiche', 'Position', 'Have you already served as a Reviewer for IJCNN or WCCI conferences?']
df5.drop(columns_drop, axis=1, inplace=True)


# Renaming columns name
df5.rename(columns={"Middle Name":"Middle Initial", "E-mail address (if applicable, the one used for your CMT account) ":"Email",
                    "Organization (University, Company, ...) ":"Organization"},
            inplace=True)


# Menaging the middle name initial
for k in range(len(df5)):
    x = df5.iloc[k]['Middle Initial']
    if not pd.isna(x):
        df5.iloc[k]['Middle Initial'] = x[0].upper() + '.'


# Print the number of Reviewers
N_Rev_5 = len(df5)
print('Number of Reviewers:', N_Rev_5)


# Check for email validity
em = list(df5['Email'])
_, res = ut.test_emails(em)

# Print the incorrect email addresses
if len(res) > 0:
    print("Please, check the following email addresses:")
    for n, j in enumerate(res):
        print(n+1, ':', em[j])
else:
    print("All email addresses are correct")


# Write to the "Tab Delimited" text file
df5.to_csv(output_file+'.txt', sep='\t', header=False, index=False)
df5.to_excel(output_file+'.xlsx', index=False)



# %% Merging al data in a single DataFrame and file

# Setting the file names
dest = './report/'
input_file_1 = dest + 'Reviewers1.xlsx'
input_file_2 = dest + 'Reviewers2.xlsx'
input_file_3 = dest + 'Reviewers3.xlsx'
input_file_4 = dest + 'Reviewers4.xlsx'
input_file_5 = dest + 'Reviewers5.xlsx'
output_file_E  = dest + 'Reviewers.xlsx'
output_file_T  = dest + 'Reviewers.txt'


# Reading the input files
df1 = pd.read_excel(input_file_1)
df2 = pd.read_excel(input_file_2)
df3 = pd.read_excel(input_file_3)
df4 = pd.read_excel(input_file_4)
df5 = pd.read_excel(input_file_5)


# Print the number of Reviewers
N_Rev_tot = len(df1) + len(df2) + len(df3) + len(df4) + len(df5)
print('Number of Reviewers:', N_Rev_tot)


# Merging all DataFrames
df = pd.concat([df1, df2, df3, df4, df5], axis=0)


# Removing duplicated rows
df = df.drop_duplicates(subset=['First Name', 'Last Name', 'Organization'])


# Print the number of Reviewers
N_Rev_all = len(df)
print('Total number of Reviewers: {}, after removing {} duplicates'.format(N_Rev_all, N_Rev_tot-N_Rev_all))


# Write to the Excel and  "Tab Delimited" text file
df.to_excel(output_file_E, index=False)
df.to_csv(output_file_T, sep='\t', header=False, index=False)




# %% Split a long file into 10 smaller files

# Setting the file names
dest = './report/'
input_file = dest + 'Reviewers.xlsx'
df = pd.read_excel(input_file)
# input_file = 'Reviewers.txt'
#df = pd.read_csv(input_file, sep='\t', header=None)

N = int(len(df)/10)

# Selecting sub-parts
df1 = df.iloc[:N]
df2 = df.iloc[N:2*N]
df3 = df.iloc[2*N:3*N]
df4 = df.iloc[3*N:4*N]
df5 = df.iloc[4*N:5*N]
df6 = df.iloc[5*N:6*N]
df7 = df.iloc[6*N:7*N]
df8 = df.iloc[7*N:8*N]
df9 = df.iloc[8*N:9*N]
df10 = df.iloc[9*N:]


# Saving separate files
df1.to_csv(dest + 'Reviewers1.txt', sep='\t', header=False, index=False)
df2.to_csv(dest + 'Reviewers2.txt', sep='\t', header=False, index=False)
df3.to_csv(dest + 'Reviewers3.txt', sep='\t', header=False, index=False)
df4.to_csv(dest + 'Reviewers4.txt', sep='\t', header=False, index=False)
df5.to_csv(dest + 'Reviewers5.txt', sep='\t', header=False, index=False)
df6.to_csv(dest + 'Reviewers6.txt', sep='\t', header=False, index=False)
df7.to_csv(dest + 'Reviewers7.txt', sep='\t', header=False, index=False)
df8.to_csv(dest + 'Reviewers8.txt', sep='\t', header=False, index=False)
df9.to_csv(dest + 'Reviewers9.txt', sep='\t', header=False, index=False)
df10.to_csv(dest + 'Reviewers10.txt', sep='\t', header=False, index=False)
